### ISSUE TITLE
RuntimeError: Function 'PowBackward0' returned nan values in its 0th output

### ISSUE THREAD

**Issue by wayen820** [HaiyuWu/Vec2Face#9]
作者您好，非常感谢您的优秀工作，我在尝试训练的时候遇到了如下错误，是在训练途中爆出来的，这个如何修改？

/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/autograd/__init__.py:276: UserWarning: Error detected in PowBackward0. Traceback of forward call that caused the error:
  File "vec2face.py", line 264, in <module>
    main(args)
  File "vec2face.py", line 223, in main
    train_stats = train_one_epoch(
  File "/home/weili/kneron_fr_ws/arcface_torch_20230323/thirds/Vec2Face/engine_vec2face.py", line 59, in train_one_epoch
    ae_loss, d_loss, token_loss, rec_loss, ssim_loss, p_loss, feature_loss = loss(im_features,
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/weili/kneron_fr_ws/arcface_torch_20230323/thirds/Vec2Face/pixel_generator/vec2face/taming/modules/discriminator_loss.py", line 100, in forward
    p_loss = self.perceptual_loss(image, gt_img) * 2
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/weili/kneron_fr_ws/arcface_torch_20230323/thirds/Vec2Face/lpips/lpips.py", line 39, in forward
    diffs[kk] = (feats0[kk] - feats1[kk]) ** 2
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/_tensor.py", line 32, in wrapped
    return f(*args, **kwargs)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "vec2face.py", line 264, in <module>
    main(args)
  File "vec2face.py", line 223, in main
    train_stats = train_one_epoch(
  File "/home/weili/kneron_fr_ws/arcface_torch_20230323/thirds/Vec2Face/engine_vec2face.py", line 59, in train_one_epoch
    ae_loss, d_loss, token_loss, rec_loss, ssim_loss, p_loss, feature_loss = loss(im_features,
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/weili/kneron_fr_ws/arcface_torch_20230323/thirds/Vec2Face/pixel_generator/vec2face/taming/modules/discriminator_loss.py", line 121, in forward
    d_weight = self.calculate_adaptive_weight(nll_loss, g_loss, last_layer=last_layer)
  File "/home/weili/kneron_fr_ws/arcface_torch_20230323/thirds/Vec2Face/pixel_generator/vec2face/taming/modules/discriminator_loss.py", line 79, in calculate_adaptive_weight
    nll_grads = torch.autograd.grad(nll_loss, last_layer, retain_graph=True)[0]
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/autograd/__init__.py", line 276, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197761 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197763 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197764 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197765 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197766 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197767 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 197768 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 197762) of binary: /home/weili/miniconda3/envs/vec2face/bin/python
Traceback (most recent call last):
  File "/home/weili/miniconda3/envs/vec2face/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.0', 'console_scripts', 'torchrun')())
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/weili/miniconda3/envs/vec2face/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by HaiyuWu** [comment]
Did you use a larger learning rate? I met this error when I used a large learning rate.

**Comment by kk1153** [comment]
I am facing the same issue. Tried different learning rates and also the one listed in the README but keep running into this same issue.

**Comment by HaiyuWu** [comment]
I have changed my code for training stability. It should work better with the current code. If you have tried the new code, could you share the error screen with me, so that we can discuss how to solve it?

**Comment by kk1153** [comment]
I am using the latest code. 

Here is the error:

  train_stats = train_one_epoch(                                                                                                                                                                        [37/1628]
  File "/home/abc/Codes/vec2face/engine_vec2face.py", line 91, in train_one_epoch                                                                                                                         
    ae_loss, d_loss, token_loss, rec_loss, ssim_loss, p_loss, feature_loss = loss(im_features,                                                                                                                     
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl                                                             
    return self._call_impl(*args, **kwargs)                                                                                                                                                                        
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl                                                                     
    return forward_call(*args, **kwargs)                                                                                                                                                                           
  File "/home/abc/Codes/vec2face/pixel_generator/vec2face/taming/modules/discriminator_loss.py", line 123, in forward                                                                                     
    ae_loss = nll_loss + d_weight * disc_factor * g_loss                                                                                                                                                           
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)                                                                                                                                     
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                                                                                                   
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                                                                                                     
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                                                                                                     
RuntimeErrorRuntimeError: : Function 'MulBackward0' returned nan values in its 0th output.Function 'MulBackward0' returned nan values in its 0th output.                                                           
                                                                                                                                                                                                                   
    model_grad_norm, disc_grad_norm = loss_scaler(ae_loss, d_loss, optimizer, dis_optimizer,                                                                                                                       
  File "/home/abc/Codes/vec2face/util/misc.py", line 262, in __call__                                                                                                                                     
    self._scaler.scale(ae_loss).backward()                                                                                                                                                                         
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward                                                                                  
    torch.autograd.backward(                                                                                                                                                                                       
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward                                                                        
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                                                                                                 
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/abc/Codes/vec2face/vec2face.py", line 282, in <module>                                                                                                                                      
    main(args)                                                                                                                                                                                                     
  File "/home/abc/Codes/vec2face/vec2face.py", line 229, in main                                                                                                                                          
    train_stats = train_one_epoch(                                                                                                                                                                                 
  File "/home/abc/Codes/vec2face/engine_vec2face.py", line 103, in train_one_epoch                                                                                                                        
    model_grad_norm, disc_grad_norm = loss_scaler(ae_loss, d_loss, optimizer, dis_optimizer,                                                                                                                       
  File "/home/abc/Codes/vec2face/util/misc.py", line 262, in __call__                                                                                                                                     
    self._scaler.scale(ae_loss).backward()                                                                                                                                                                         
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward                                                                                  
    torch.autograd.backward(                                                                                                                                                                                       
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward                                                                        
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                                                                                                                 
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.                                                                                                                                       
[2025-01-13 11:10:27,270] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 3381097) of binary: /home/abc/Codes/facereco_model/venv_faceid/bin/python3.10   
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/abc/Codes/facereco_model/venv_faceid/bin/torchrun", line 8, in <module>           
    sys.exit(main())                                                                                     
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper                                       
    return f(*args, **kwargs)                                                                                                                                                                                      
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main                                                                              
    run(args)                                                                                                                                                                                                      
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run                                                                               
    elastic_launch(                                                                                      
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__                                                                 
    return launch_agent(self._config, self._entrypoint, list(args))                                      
  File "/home/abc/Codes/facereco_model/venv_faceid/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent                                                             
    raise ChildFailedError(                                                                              
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by HaiyuWu** [comment]
Thanks for your feedback and sorry for the late reply. I will try to reproduce this error on my system. However, if it is possible, you can also try to locate where the numerical instability happens and clip the number range to make sure 0 does not occur at the denominator.

**Comment by kk1153** [comment]
I think it is occuring due to mixed precision training. When i change the         
self._scaler = torch.cuda.amp.GradScaler(init_scale=1024, growth_interval=2000) with init_scale to 1024. It does not give this error for 1 epoch of training and then throws the same error after 1st epoch.

**Comment by HaiyuWu** [comment]
I realize that NaN error mainly occurs at the normalize_tensor function in the lpips.py file.
```
def normalize_tensor(x):
    # for numerical stability
    norm = torch.norm(x, 2, 1, True).clamp(min=1e-4)
    output = torch.div(x, norm)
    return output
```
I enlarged the lower bound of the tensor norm, then I did not see the NaN again.
I hope this solves the NaN problem.

**Comment by LilHsi0628** [comment]
I also encountered the same error, how can I resolve it?

**Comment by HaiyuWu** [comment]
I have tried to reproduce the same error on my side but I don't see this error.
Here are a few suggestions:
1. Without the discriminator, the model still works well. I suggest disabling the discriminator during the training.
2. Set growth_interval to a smaller number for example 200 or 100. This can avoid the unstable training.
3. Update the code to the latest version, because I have updated the parts that cause the numerical instability.
4. If you still encounter the same issue, try to resume the training. Some one told me that this way works.

**Comment by LilHsi0628** [comment]
Fine, thanks, I’ll have a try.
